<?php

namespace LOCKSSOMatic\CrudBundle\Tests\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-15 at 13:23:44.
 */
class AuPropertyTest extends AbstractEntityTestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    public function testHasParentNull() {
        $this->assertNull($this->references->getReference('auprop-root')->getParent());
        $this->assertFalse($this->references->getReference('auprop-root')->hasParent());
    }

    public function testHasParent() {
        $this->assertNotNull($this->references->getReference('auprop-child')->getParent());
        $this->assertTrue($this->references->getReference('auprop-child')->hasParent());
    }

    public function testHasChildrenNull() {
        $leaf = $this->references->getReference('auprop-leaf');
        $this->assertEquals(0, count($leaf->getChildren()));
        $this->assertFalse($this->references->getReference('auprop-leaf')->hasChildren());
    }

    public function testHasChildren() {
        $child = $this->references->getReference('auprop-child');
        $this->assertEquals(2, count($child->getChildren()));
        $this->assertTrue($this->references->getReference('auprop-child')->hasChildren());
    }
}
