<?php

namespace LOCKSSOMatic\CRUDBundle\Tests\Entity;

use LOCKSSOMatic\CRUDBundle\Entity\ContentBuilder;
use LOCKSSOMatic\SWORDBundle\Utilities\Namespaces;
use PHPUnit_Framework_TestCase;
use SimpleXMLElement;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-14 at 10:48:17.
 */
class ContentBuilderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LOCKSSOMatic\CRUDBundle\Entity\ContentBuilder::fromSimpleXML
     * @todo   Implement testFromSimpleXML().
     */
    public function testFromSimpleXML()
    {
        $doc = '<lom:content xmlns:lom="http://lockssomatic.info/SWORD2" size="102400" checksumType="md5" checksumValue="bd4a9b642562547754086de2dab26b7d">http://contentprovider.example.org/download/file1.zip</lom:content>';
        $entry = new SimpleXMLElement($doc);
        $builder = new ContentBuilder();
        $content = $builder->fromSimpleXML($entry);
        $this->assertInstanceOf('LOCKSSOMatic\CRUDBundle\Entity\Content', $content);
        $this->assertEquals('102400', $content->getSize());
        $this->assertEquals('md5', $content->getChecksumType());
        $this->assertEquals('bd4a9b642562547754086de2dab26b7d', $content->getChecksumValue());
        $this->assertEquals('http://contentprovider.example.org/download/file1.zip', $content->getUrl());        
    }

}
