<?php

/* 
 * The MIT License
 *
 * Copyright (c) 2014 Mark Jordan, mjordan@sfu.ca.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

namespace LOCKSSOMatic\CRUDBundle\Tests\Entity;

use LOCKSSOMatic\CRUDBundle\Entity\ContentBuilder;
use LOCKSSOMatic\SWORDBundle\Utilities\Namespaces;
use PHPUnit_Framework_TestCase;
use SimpleXMLElement;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-14 at 10:48:17.
 */
class ContentBuilderTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers LOCKSSOMatic\CRUDBundle\Entity\ContentBuilder::fromSimpleXML
     * @todo   Implement testFromSimpleXML().
     */
    public function testFromSimpleXML()
    {
        $doc = '<lom:content xmlns:lom="http://lockssomatic.info/SWORD2" size="102400" checksumType="md5" checksumValue="bd4a9b642562547754086de2dab26b7d">http://contentprovider.example.org/download/file1.zip</lom:content>';
        $entry = new SimpleXMLElement($doc);
        $builder = new ContentBuilder();
        $content = $builder->fromSimpleXML($entry);
        $this->assertInstanceOf('LOCKSSOMatic\CRUDBundle\Entity\Content', $content);
        $this->assertEquals('102400', $content->getSize());
        $this->assertEquals('md5', $content->getChecksumType());
        $this->assertEquals('bd4a9b642562547754086de2dab26b7d', $content->getChecksumValue());
        $this->assertEquals('http://contentprovider.example.org/download/file1.zip', $content->getUrl());        
    }

}
