<?php

namespace LOCKSSOMatic\CRUDBundle\Entity;

use LOCKSSOMatic\SWORDBundle\Utilities\Namespaces;
use PHPUnit_Framework_TestCase;
use SimpleXMLElement;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-14 at 10:08:41.
 */
class DepositBuilderTest extends PHPUnit_Framework_TestCase
{

    public function testFromSimpleXML()
    {
        $doc = <<<'ENDDOC'
<entry xmlns="http://www.w3.org/2005/Atom"
        xmlns:dcterms="http://purl.org/dc/terms/"
        xmlns:lom="http://lockssomatic.info/SWORD2">
    <title>Some content to preserve.</title>
    <id>urn:uuid:1225c695-cfb8-4ebb-aaaa-80da344efa6a</id>
    <updated>2013-10-07T17:17:08Z</updated>
    <author><name>Institute of Foo Studies</name></author>
    <summary type="text">Content deposit.</summary>
    <lom:content size="102400" checksumType="md5" checksumValue="bd4a9b642562547754086de2dab26b7d">http://contentprovider.example.org/download/file1.zip</lom:content>
</entry>   
ENDDOC;
        $entry = new SimpleXMLElement($doc);
        $ns = new Namespaces();
        $ns->registerNamespaces($entry);
        
        $builder = new DepositBuilder();
        $deposit = $builder->fromSimpleXML($entry);
        $this->assertInstanceOf('LOCKSSOMatic\CRUDBundle\Entity\Deposits', $deposit);
        $this->assertEquals('Some content to preserve.', $deposit->getTitle());
        $this->assertEquals('1225c695-cfb8-4ebb-aaaa-80da344efa6a', $deposit->getUuid());
    }

}
