<?php

namespace LOCKSSOMatic\CrudBundle\Tests\Entity;

use LOCKSSOMatic\CrudBundle\Entity\Pln;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-15 at 12:04:12.
 */
class PlnTest extends AbstractEntityTestCase
{

    /**
     * @var Pln
     */
    protected $pln;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->pln = $this->references->getReference('pln-franklin');
    }

    public function testDefaults() {
        $this->assertEquals('franklin', $this->pln->getName());
    }

}
