<?php

namespace LOCKSSOMatic\CrudBundle\Tests\Entity;

use LOCKSSOMatic\CrudBundle\Entity\Plugin;
use LOCKSSOMatic\CrudBundle\Entity\PluginProperty;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-15 at 13:23:44.
 */
class PluginPropertyTest extends AbstractEntityTestCase
{

    /**
     * @var Plugin
     */
    protected $plugin;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->plugin = $this->references->getReference('plugin');
    }

    public function testGetNullParent() {
        $p1 = $this->references->getReference('prop_name');
        $this->assertFalse($p1->hasParent());
        $this->assertNull($p1->getParent());
    }

    public function testGetParent() {
        /** @var PluginProperty $prop */
        $prop = $this->references->getReference('plugin_configparamdescr');
        $this->assertTrue($prop->hasParent());
        $parent = $prop->getParent();
        $this->assertNotNull($parent);
        $this->assertEquals('plugin_config_props', $parent->getPropertyKey());
    }

    public function testGetChildren() {
        $prop = $this->references->getReference('prop_config');
        $this->assertTrue($prop->hasChildren());

        $children = $prop->getChildren();
        $this->assertEquals(2, count($children));
        $this->assertEquals('configparamdescr', $children[0]->getPropertyKey());
        $this->assertEquals('configparamdescr', $children[1]->getPropertyKey());
    }

}
