services:
    app.form.profile:
        class: LOCKSSOMatic\UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: lom_user_profile }

    app.registration.listener:
        class: LOCKSSOMatic\UserBundle\EventListener\RegistrationListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["@router"]
        
    lom.twig.lom_userextension:
        class: LOCKSSOMatic\UserBundle\Twig\UsersExtension
        arguments: [@doctrine]
        tags:
            - { name: twig.extension }

    lom.access:
        class: LOCKSSOMatic\UserBundle\Security\Services\Access
        calls:
            - [ setAuthChecker, ["@security.authorization_checker"]]
            - [ setTokenStorage, ["@security.token_storage"]]
            - [ setAclManager, ["@problematic.acl_manager"]]
            - [ setAclProvider, ["@security.acl.provider"]]
#            - [ setRegistry, ["@doctrine"] ]
            - [ setLogger, ["@logger"] ]
        tags:
            - { name: acl.check }

    lom.message:
        class: LOCKSSOMatic\UserBundle\Service\MessageService
        calls:
            - [ setLogger, ["@logger"] ]
            - [ setRegistry, ["@doctrine"] ]
            - [ setTokenStorage, ["@security.token_storage"]]