<?php

namespace LOCKSSOMatic\LockssBundle\Tests\Services;

use LOCKSSOMatic\CoreBundle\Utilities\AbstractTestCase;
use LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-21 at 10:45:46.
 */
class PLNPluginImportServiceTest extends AbstractTestCase
{
    /**
     * @var PLNPluginImportService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = $this->getContainer()->get('pln_plugin_importer');
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::importJarFile
     *
     * @todo   Implement testImportJarFile().
     */
    public function testImportJarFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::getPluginPath
     *
     * @todo   Implement testGetPluginPath().
     */
    public function testGetPluginPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::findXmlPropString
     *
     * @todo   Implement testFindXmlPropString().
     */
    public function testFindXmlPropString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::findXmlPropElement
     *
     * @todo   Implement testFindXmlPropElement().
     */
    public function testFindXmlPropElement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::newPluginProperty
     *
     * @todo   Implement testNewPluginProperty().
     */
    public function testNewPluginProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::buildPlugin
     *
     * @todo   Implement testBuildPlugin().
     */
    public function testBuildPlugin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LOCKSSOMatic\LockssBundle\Services\PLNPluginImportService::addProperties
     *
     * @todo   Implement testAddProperties().
     */
    public function testAddProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
