sudo: false

language: php

env:
    global:
        - SYMFONY_ENV=test
        - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  
cache: apt

before_script:
  - echo 'date.timezone = America/Vancouver' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install -n -o

script:
  - ./bin/phpunit

