
services:

    crud.builder.deposit:
        class: LOCKSSOMatic\CrudBundle\Service\DepositBuilder
        calls:
            - [ setLogger, ["@logger"] ]
            - [ setRegistry, ["@doctrine"] ]
            - [ setAuBuilder, ["@crud.builder.au"] ]

    crud.builder.content:
        class: LOCKSSOMatic\CrudBundle\Service\ContentBuilder
        calls:
            - [ setLogger, ["@logger"] ]
            - [ setRegistry, ["@doctrine"] ]

    crud.builder.au:
        class: LOCKSSOMatic\CrudBundle\Service\AuBuilder
        calls:
            - [ setLogger, ["@logger"] ]
            - [ setRegistry, ["@doctrine"] ]
            - [ setPropertyGenerator, ["@crud.propertygenerator"]]
    
    crud.propertygenerator:
        class: LOCKSSOMatic\CrudBundle\Service\AuPropertyGenerator
        calls:
            - [ setLogger, ["@logger"] ]
            - [ setRegistry, ["@doctrine"] ]
            - [ setRouter, ["@router"]]
        
