LOCKSSOMatic\CrudBundle\Entity\Au:
    type: entity
    table: aus
    indexes:
        IDX_2D10D530C8BA1A08:
            columns:
                - pln_id
        IDX_2D10D530EC46F62F:
            columns:
                - plugin_id
        IDX_2D10D530DCEFBC03:
            columns:
                - contentprovider_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        managed:
            type: boolean
            nullable: false
            comment: ''
        auid:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
        manifestUrl:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
            column: manifest_url
        comment:
            type: string
            nullable: true
            length: 512
            fixed: false
            comment: ''
    manyToOne:
        pln:
            targetEntity: Pln
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pln_id:
                    referencedColumnName: id
            orphanRemoval: false
        contentprovider:
            targetEntity: ContentProvider
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contentprovider_id:
                    referencedColumnName: id
            orphanRemoval: false
        plugin:
            targetEntity: Plugin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
