LOCKSSOMatic\CrudBundle\Entity\AuProperty:
    type: entity
    table: au_properties
    indexes:
        IDX_EFF7C3EEA3D201B3:
            columns:
                - au_id
        IDX_EFF7C3EE727ACA70:
            columns:
                - parent_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        propertyKey:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: property_value
    manyToOne:
        parent:
            targetEntity: AuProperty
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
        au:
            targetEntity: Au
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                au_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
