LOCKSSOMatic\CrudBundle\Entity\Box:
    type: entity
    table: boxes
    indexes:
        IDX_CDF1B2E9C8BA1A08:
            columns:
                - pln_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hostname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        ipAddress:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
            column: ip_address
        username:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
    manyToOne:
        pln:
            targetEntity: Pln
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pln_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
