LOCKSSOMatic\CrudBundle\Entity\BoxStatus:
    type: entity
    table: box_status
    indexes:
        IDX_D5A8258ADC3B2062:
            columns:
                - box_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        queryDate:
            type: datetime
            nullable: false
            comment: ''
            column: query_date
        propertyKey:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: property_value
    manyToOne:
        box:
            targetEntity: Box
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                box_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
