LOCKSSOMatic\CrudBundle\Entity\ContentOwner:
    type: entity
    table: content_owners
    indexes:
        IDX_2A44E256EC46F62F:
            columns:
                - plugin_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        emailAddress:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: email_address
    manyToOne:
        plugin:
            targetEntity: Plugin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
