LOCKSSOMatic\CrudBundle\Entity\Deposit:
    type: entity
    table: deposits
    indexes:
        IDX_449E9C9ED5F0A8C4:
            columns:
                - content_provider_id
        uuid:
            columns:
                - uuid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            nullable: false
            length: 36
            fixed: false
            comment: ''
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        summary:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        dateDeposited:
            type: datetime
            nullable: false
            comment: ''
            column: date_deposited
    manyToOne:
        contentProvider:
            targetEntity: ContentProvider
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                content_provider_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
