LOCKSSOMatic\CrudBundle\Entity\Pln:
    type: entity
    table: plns
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        propserver:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: propServer
        propsPath:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: props_path
    lifecycleCallbacks: {  }
