LOCKSSOMatic\CrudBundle\Entity\Plugin:
    type: entity
    table: plugins
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
