services:
    lom.filepaths:
        class: LOCKSSOMatic\CoreBundle\Services\FilePaths
        calls:
            - [ setLogger, ["@monolog.logger" ]]
            - [ setKernelEnv, ["%kernel.root_dir%"]]
            