<?php

namespace LOCKSSOMatic\LoggingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogEntryRepository extends EntityRepository
{
}
